//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Input/PlinkoControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlinkoControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlinkoControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlinkoControls"",
    ""maps"": [
        {
            ""name"": ""Plinko"",
            ""id"": ""a981cd09-7d96-40ca-9d89-91eca1f972bb"",
            ""actions"": [
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""d3f3687a-5c50-460b-9b3a-04b34b641265"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""81bd90d8-5947-4b57-820b-54006989790e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5b5d8f00-8bac-4e32-b97c-4500f0c3ceb6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08b904ff-bc1f-4571-bafc-f3fb26a45581"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cef7d56-934d-43ea-8287-1ea0796787f0"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""874c8d4f-14c9-4c80-8948-14a523b16486"",
                    ""path"": ""<Touchscreen>/touch*/Press"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SlimeHole"",
            ""id"": ""64c7f564-d3bb-4fd5-9fcf-bb67f95b4e60"",
            ""actions"": [
                {
                    ""name"": ""Input"",
                    ""type"": ""Value"",
                    ""id"": ""4b5c009b-e682-4141-8fc3-8bc506858222"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""17cc5ae1-2b04-49bc-adf1-e5af0406bce3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""9511f887-8862-4218-a389-977aa8725989"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Input"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9acf3c30-1e40-48e7-9fd8-ae5766a20cd0"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Input"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c58e13e5-1ab7-49d2-b8df-dc98e65ce0db"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Input"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4fded5c2-5422-420a-b81d-455e214252e3"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Input"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0ebd2bd9-efd9-4813-9e4f-d506850a062f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""267aa95e-273e-4e48-97fa-12dc213b53b7"",
                    ""path"": ""<Touchscreen>/touch*/Press"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Plinko
        m_Plinko = asset.FindActionMap("Plinko", throwIfNotFound: true);
        m_Plinko_Drop = m_Plinko.FindAction("Drop", throwIfNotFound: true);
        m_Plinko_Reset = m_Plinko.FindAction("Reset", throwIfNotFound: true);
        // SlimeHole
        m_SlimeHole = asset.FindActionMap("SlimeHole", throwIfNotFound: true);
        m_SlimeHole_Input = m_SlimeHole.FindAction("Input", throwIfNotFound: true);
        m_SlimeHole_Reset = m_SlimeHole.FindAction("Reset", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Plinko
    private readonly InputActionMap m_Plinko;
    private List<IPlinkoActions> m_PlinkoActionsCallbackInterfaces = new List<IPlinkoActions>();
    private readonly InputAction m_Plinko_Drop;
    private readonly InputAction m_Plinko_Reset;
    public struct PlinkoActions
    {
        private @PlinkoControls m_Wrapper;
        public PlinkoActions(@PlinkoControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Drop => m_Wrapper.m_Plinko_Drop;
        public InputAction @Reset => m_Wrapper.m_Plinko_Reset;
        public InputActionMap Get() { return m_Wrapper.m_Plinko; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlinkoActions set) { return set.Get(); }
        public void AddCallbacks(IPlinkoActions instance)
        {
            if (instance == null || m_Wrapper.m_PlinkoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlinkoActionsCallbackInterfaces.Add(instance);
            @Drop.started += instance.OnDrop;
            @Drop.performed += instance.OnDrop;
            @Drop.canceled += instance.OnDrop;
            @Reset.started += instance.OnReset;
            @Reset.performed += instance.OnReset;
            @Reset.canceled += instance.OnReset;
        }

        private void UnregisterCallbacks(IPlinkoActions instance)
        {
            @Drop.started -= instance.OnDrop;
            @Drop.performed -= instance.OnDrop;
            @Drop.canceled -= instance.OnDrop;
            @Reset.started -= instance.OnReset;
            @Reset.performed -= instance.OnReset;
            @Reset.canceled -= instance.OnReset;
        }

        public void RemoveCallbacks(IPlinkoActions instance)
        {
            if (m_Wrapper.m_PlinkoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlinkoActions instance)
        {
            foreach (var item in m_Wrapper.m_PlinkoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlinkoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlinkoActions @Plinko => new PlinkoActions(this);

    // SlimeHole
    private readonly InputActionMap m_SlimeHole;
    private List<ISlimeHoleActions> m_SlimeHoleActionsCallbackInterfaces = new List<ISlimeHoleActions>();
    private readonly InputAction m_SlimeHole_Input;
    private readonly InputAction m_SlimeHole_Reset;
    public struct SlimeHoleActions
    {
        private @PlinkoControls m_Wrapper;
        public SlimeHoleActions(@PlinkoControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Input => m_Wrapper.m_SlimeHole_Input;
        public InputAction @Reset => m_Wrapper.m_SlimeHole_Reset;
        public InputActionMap Get() { return m_Wrapper.m_SlimeHole; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SlimeHoleActions set) { return set.Get(); }
        public void AddCallbacks(ISlimeHoleActions instance)
        {
            if (instance == null || m_Wrapper.m_SlimeHoleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SlimeHoleActionsCallbackInterfaces.Add(instance);
            @Input.started += instance.OnInput;
            @Input.performed += instance.OnInput;
            @Input.canceled += instance.OnInput;
            @Reset.started += instance.OnReset;
            @Reset.performed += instance.OnReset;
            @Reset.canceled += instance.OnReset;
        }

        private void UnregisterCallbacks(ISlimeHoleActions instance)
        {
            @Input.started -= instance.OnInput;
            @Input.performed -= instance.OnInput;
            @Input.canceled -= instance.OnInput;
            @Reset.started -= instance.OnReset;
            @Reset.performed -= instance.OnReset;
            @Reset.canceled -= instance.OnReset;
        }

        public void RemoveCallbacks(ISlimeHoleActions instance)
        {
            if (m_Wrapper.m_SlimeHoleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISlimeHoleActions instance)
        {
            foreach (var item in m_Wrapper.m_SlimeHoleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SlimeHoleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SlimeHoleActions @SlimeHole => new SlimeHoleActions(this);
    public interface IPlinkoActions
    {
        void OnDrop(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
    }
    public interface ISlimeHoleActions
    {
        void OnInput(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
    }
}
